// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwmSBero4Ux-ZRV7IPeMaGQ4Tb0Wfi8m8',
    appId: '1:479459859528:web:db3eb499eeb6d4d4258c7d',
    messagingSenderId: '479459859528',
    projectId: 'ticktok-whasup',
    authDomain: 'ticktok-whasup.firebaseapp.com',
    storageBucket: 'ticktok-whasup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCci5a5a2P7tDWjyTsgIs3NVkLh3L8ogb8',
    appId: '1:479459859528:android:727b544ae023eea8258c7d',
    messagingSenderId: '479459859528',
    projectId: 'ticktok-whasup',
    storageBucket: 'ticktok-whasup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3kZkJaxTMiKDy20zV9An_jkwZ0YjGmRY',
    appId: '1:479459859528:ios:e419fed9735d1e5f258c7d',
    messagingSenderId: '479459859528',
    projectId: 'ticktok-whasup',
    storageBucket: 'ticktok-whasup.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}